//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_RegistroVacunas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaccinationRecord
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public VaccinationRecord()
        {
            this.VaccinationSchedule = new HashSet<VaccinationSchedule>();
        }
    
        public int VaccinationRecordID { get; set; }
        public int vaccineQuantity { get; set; }
        public System.TimeSpan doseTime { get; set; }
        public byte nursesQuantity { get; set; }
        public System.DateTime startDate { get; set; }
        public System.TimeSpan startAttention { get; set; }
        public System.TimeSpan endAttention { get; set; }
        public int UserID { get; set; }
    
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<VaccinationSchedule> VaccinationSchedule { get; set; }
    }
}
