//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto_RegistroVacunas.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class VaccinationAppointment
    {
        public int VaccionationRecordID { get; set; }
        public byte expiration { get; set; }
        public System.DateTime vaccinationDay { get; set; }
        public int UserID { get; set; }
    
        public virtual User User { get; set; }
    }
}
